/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Agent memory harness over a local Turso/SQLite database: save and search
 * memories with vector similarity, search the subject graph, run the dream
 * (subject extraction) pipeline, and run one memory-augmented chat turn.
 */
export declare class Harness {
  /**
   * Opens (creating if needed) the database at `dbPath`, applies
   * migrations, and wires the memory store with the configured embedder.
   * Static factory: `const h = await Harness.open("./mem.db")`.
   */
  static open(dbPath: string, opts?: OpenOptions | undefined | null): Promise<Harness>
  /** Creates the user row if it does not exist (idempotent). */
  seedUser(uid: string): Promise<void>
  /**
   * Saves one memory pair from a JSON object (camelCase keys:
   * `userId`, `prompt`, `response`, plus optional `id`, `title`,
   * `summary`, `sessionId`, `source`, `timestamp` (RFC3339), `daysAgo`,
   * `subjects: [{text, description, key}]`). Embeds the pair and each
   * subject; returns the stored memory as a JSON object.
   */
  saveMemory(json: any): Promise<any>
  /**
   * Vector-searches the user's memories for `query`; returns memory JSON
   * objects ordered by descending similarity.
   */
  searchMemories(uid: string, query: string, opts?: SearchOptions | undefined | null): Promise<Array<any>>
  /**
   * Vector-searches the user's subject graph for `query`; returns subject
   * JSON objects ordered by descending similarity.
   */
  searchSubjects(uid: string, query: string): Promise<Array<any>>
  /**
   * Runs the dream pipeline over the user's recent memories: extracts
   * durable subjects with the configured chat model, dedups/merges them
   * into the subject graph, links them to source pairs, and optionally
   * refines merged descriptions. Returns the DreamReport as JSON.
   */
  dream(uid: string, opts?: ModelOptions | undefined | null): Promise<any>
  /**
   * Runs one memory-augmented chat turn: retrieves prompt memories,
   * exposes the five memory tools to the agent loop, and (by default)
   * saves the exchange as a new memory pair.
   */
  chat(uid: string, message: string, opts?: ModelOptions | undefined | null): Promise<ChatTurnResult>
}

/** Result of one [`Harness::chat`] turn. */
export interface ChatTurnResult {
  /** Final assistant text. */
  response: string
  /** Total monetary cost across model calls (0 for local providers). */
  cost: number
  /** Names of the tools the agent called, in order. */
  toolCalls: Array<string>
}

/** Returns the ditto-harness crate version. */
export declare function harnessVersion(): string

/** Chat-model selection shared by [`Harness::dream`] and [`Harness::chat`]. */
export interface ModelOptions {
  /** `"ollama"` (default), `"openrouter"`, or `"vllm"`. */
  provider?: string
  /**
   * Model name. Default for ollama: `gemma3:4b`. Required for
   * openrouter/vllm.
   */
  model?: string
  /** Provider base URL (ollama/vllm). Required for vllm. */
  baseUrl?: string
  /** API key for openrouter; falls back to `OPENROUTER_API_KEY`. */
  apiKey?: string
  /** Chat session id. Default `"main"`. (chat only) */
  sessionId?: string
  /** Max agent-loop turns. Default 8. (chat only) */
  maxTurns?: number
  /** Persist the exchange as a memory pair. Default true. (chat only) */
  saveMemory?: boolean
  /** Cap on memories considered, newest first. Default 128. (dream only) */
  maxMemories?: number
  /** Run the dream refine stage. Default true. (dream only) */
  refine?: boolean
}

/** Options for [`Harness::open`]. */
export interface OpenOptions {
  /**
   * Base URL for the local Ollama server used for embeddings.
   * Default: `http://localhost:11434`.
   */
  ollamaBaseUrl?: string
  /**
   * Embedder backend: `"ollama"` (default, embeddinggemma 768 dims) or
   * `"hash"` (deterministic offline stub for tests/smoke runs).
   */
  embedder?: string
}

/** Options for [`Harness::search_memories`]. */
export interface SearchOptions {
  /** Restrict to one session; omit to search all sessions. */
  sessionId?: string
  /** Max results. Default 8. */
  limit?: number
  /** Minimum cosine similarity. Default 0.15. */
  minSimilarity?: number
}
