// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const createMemoryPair = `-- name: CreateMemoryPair :one
INSERT INTO memory_pairs (
    firestore_pair_id, user_id, kg_id, session_id, title, description,
    prompt, response, input, output, source, source_context, timestamp,
    timezone_offset, seed_memories, retrieval_metadata, conversation_embedding
) VALUES (
    $1, $2, $3,
    NULLIF($4, ''), NULLIF($5, ''), NULLIF($6, ''),
    NULLIF($7, ''), NULLIF($8, ''), $9, $10,
    NULLIF($11, ''), NULLIF($12, ''),
    $13, $14, $15,
    $16, $17
)
ON CONFLICT (user_id, firestore_pair_id) DO UPDATE SET
    kg_id = EXCLUDED.kg_id,
    session_id = EXCLUDED.session_id,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    prompt = EXCLUDED.prompt,
    response = EXCLUDED.response,
    input = EXCLUDED.input,
    output = EXCLUDED.output,
    source = EXCLUDED.source,
    source_context = EXCLUDED.source_context,
    timestamp = EXCLUDED.timestamp,
    timezone_offset = EXCLUDED.timezone_offset,
    seed_memories = EXCLUDED.seed_memories,
    retrieval_metadata = EXCLUDED.retrieval_metadata,
    conversation_embedding = EXCLUDED.conversation_embedding,
    updated_at = NOW()
RETURNING id, firestore_pair_id, user_id, kg_id, session_id, title, description,
    prompt, response, input, output, source, source_context, timestamp,
    timezone_offset, seed_memories, retrieval_metadata, conversation_embedding
`

type CreateMemoryPairParams struct {
	FirestorePairID       string             `json:"firestorePairId"`
	UserID                string             `json:"userId"`
	KgID                  string             `json:"kgId"`
	SessionID             interface{}        `json:"sessionId"`
	Title                 interface{}        `json:"title"`
	Description           interface{}        `json:"description"`
	Prompt                interface{}        `json:"prompt"`
	Response              interface{}        `json:"response"`
	Input                 []byte             `json:"input"`
	Output                []byte             `json:"output"`
	Source                interface{}        `json:"source"`
	SourceContext         interface{}        `json:"sourceContext"`
	Timestamp             pgtype.Timestamptz `json:"timestamp"`
	TimezoneOffset        pgtype.Int4        `json:"timezoneOffset"`
	SeedMemories          []byte             `json:"seedMemories"`
	RetrievalMetadata     []byte             `json:"retrievalMetadata"`
	ConversationEmbedding pgvector.Vector    `json:"conversationEmbedding"`
}

type CreateMemoryPairRow struct {
	ID                    pgtype.UUID        `json:"id"`
	FirestorePairID       string             `json:"firestorePairId"`
	UserID                string             `json:"userId"`
	KgID                  string             `json:"kgId"`
	SessionID             pgtype.Text        `json:"sessionId"`
	Title                 pgtype.Text        `json:"title"`
	Description           pgtype.Text        `json:"description"`
	Prompt                pgtype.Text        `json:"prompt"`
	Response              pgtype.Text        `json:"response"`
	Input                 []byte             `json:"input"`
	Output                []byte             `json:"output"`
	Source                pgtype.Text        `json:"source"`
	SourceContext         pgtype.Text        `json:"sourceContext"`
	Timestamp             pgtype.Timestamptz `json:"timestamp"`
	TimezoneOffset        pgtype.Int4        `json:"timezoneOffset"`
	SeedMemories          []byte             `json:"seedMemories"`
	RetrievalMetadata     []byte             `json:"retrievalMetadata"`
	ConversationEmbedding pgvector.Vector    `json:"conversationEmbedding"`
}

func (q *Queries) CreateMemoryPair(ctx context.Context, arg CreateMemoryPairParams) (CreateMemoryPairRow, error) {
	row := q.db.QueryRow(ctx, createMemoryPair,
		arg.FirestorePairID,
		arg.UserID,
		arg.KgID,
		arg.SessionID,
		arg.Title,
		arg.Description,
		arg.Prompt,
		arg.Response,
		arg.Input,
		arg.Output,
		arg.Source,
		arg.SourceContext,
		arg.Timestamp,
		arg.TimezoneOffset,
		arg.SeedMemories,
		arg.RetrievalMetadata,
		arg.ConversationEmbedding,
	)
	var i CreateMemoryPairRow
	err := row.Scan(
		&i.ID,
		&i.FirestorePairID,
		&i.UserID,
		&i.KgID,
		&i.SessionID,
		&i.Title,
		&i.Description,
		&i.Prompt,
		&i.Response,
		&i.Input,
		&i.Output,
		&i.Source,
		&i.SourceContext,
		&i.Timestamp,
		&i.TimezoneOffset,
		&i.SeedMemories,
		&i.RetrievalMetadata,
		&i.ConversationEmbedding,
	)
	return i, err
}

const fetchMemories = `-- name: FetchMemories :many
SELECT id, firestore_pair_id, user_id, kg_id, session_id, title, description,
    prompt, response, input, output, source, source_context, timestamp,
    timezone_offset, seed_memories, retrieval_metadata, conversation_embedding
FROM memory_pairs
WHERE user_id = $1 AND firestore_pair_id = ANY($2::text[])
ORDER BY array_position($2::text[], firestore_pair_id)
`

type FetchMemoriesParams struct {
	UserID  string   `json:"userId"`
	PairIds []string `json:"pairIds"`
}

type FetchMemoriesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	FirestorePairID       string             `json:"firestorePairId"`
	UserID                string             `json:"userId"`
	KgID                  string             `json:"kgId"`
	SessionID             pgtype.Text        `json:"sessionId"`
	Title                 pgtype.Text        `json:"title"`
	Description           pgtype.Text        `json:"description"`
	Prompt                pgtype.Text        `json:"prompt"`
	Response              pgtype.Text        `json:"response"`
	Input                 []byte             `json:"input"`
	Output                []byte             `json:"output"`
	Source                pgtype.Text        `json:"source"`
	SourceContext         pgtype.Text        `json:"sourceContext"`
	Timestamp             pgtype.Timestamptz `json:"timestamp"`
	TimezoneOffset        pgtype.Int4        `json:"timezoneOffset"`
	SeedMemories          []byte             `json:"seedMemories"`
	RetrievalMetadata     []byte             `json:"retrievalMetadata"`
	ConversationEmbedding pgvector.Vector    `json:"conversationEmbedding"`
}

func (q *Queries) FetchMemories(ctx context.Context, arg FetchMemoriesParams) ([]FetchMemoriesRow, error) {
	rows, err := q.db.Query(ctx, fetchMemories, arg.UserID, arg.PairIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchMemoriesRow
	for rows.Next() {
		var i FetchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirestorePairID,
			&i.UserID,
			&i.KgID,
			&i.SessionID,
			&i.Title,
			&i.Description,
			&i.Prompt,
			&i.Response,
			&i.Input,
			&i.Output,
			&i.Source,
			&i.SourceContext,
			&i.Timestamp,
			&i.TimezoneOffset,
			&i.SeedMemories,
			&i.RetrievalMetadata,
			&i.ConversationEmbedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSubjectMemoryPair = `-- name: LinkSubjectMemoryPair :exec
INSERT INTO subject_memory_pair_links (subject_id, pair_id, user_id, kg_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (subject_id, pair_id) DO NOTHING
`

type LinkSubjectMemoryPairParams struct {
	SubjectID pgtype.UUID `json:"subjectId"`
	PairID    pgtype.UUID `json:"pairId"`
	UserID    string      `json:"userId"`
	KgID      string      `json:"kgId"`
}

func (q *Queries) LinkSubjectMemoryPair(ctx context.Context, arg LinkSubjectMemoryPairParams) error {
	_, err := q.db.Exec(ctx, linkSubjectMemoryPair,
		arg.SubjectID,
		arg.PairID,
		arg.UserID,
		arg.KgID,
	)
	return err
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, firestore_pair_id, user_id, kg_id, session_id, title, description,
    prompt, response, input, output, source, source_context, timestamp,
    timezone_offset, seed_memories, retrieval_metadata, conversation_embedding,
    (1 - (conversation_embedding <=> $1::vector))::float8 AS similarity
FROM memory_pairs
WHERE user_id = $2 AND kg_id = $3
  AND conversation_embedding IS NOT NULL
  AND ($4::text = '' OR COALESCE(session_id, 'main') = COALESCE(NULLIF($4::text, ''), 'main'))
  AND ($5::text[] IS NULL OR firestore_pair_id != ALL($5::text[]))
  AND (1 - (conversation_embedding <=> $1::vector)) >= $6::float8
ORDER BY conversation_embedding <=> $1::vector, timestamp DESC
LIMIT $7
`

type SearchMemoriesParams struct {
	Embedding      pgvector.Vector `json:"embedding"`
	UserID         string          `json:"userId"`
	KgID           string          `json:"kgId"`
	SessionID      string          `json:"sessionId"`
	ExcludePairIds []string        `json:"excludePairIds"`
	MinSimilarity  float64         `json:"minSimilarity"`
	LimitCount     int32           `json:"limitCount"`
}

type SearchMemoriesRow struct {
	ID                    pgtype.UUID        `json:"id"`
	FirestorePairID       string             `json:"firestorePairId"`
	UserID                string             `json:"userId"`
	KgID                  string             `json:"kgId"`
	SessionID             pgtype.Text        `json:"sessionId"`
	Title                 pgtype.Text        `json:"title"`
	Description           pgtype.Text        `json:"description"`
	Prompt                pgtype.Text        `json:"prompt"`
	Response              pgtype.Text        `json:"response"`
	Input                 []byte             `json:"input"`
	Output                []byte             `json:"output"`
	Source                pgtype.Text        `json:"source"`
	SourceContext         pgtype.Text        `json:"sourceContext"`
	Timestamp             pgtype.Timestamptz `json:"timestamp"`
	TimezoneOffset        pgtype.Int4        `json:"timezoneOffset"`
	SeedMemories          []byte             `json:"seedMemories"`
	RetrievalMetadata     []byte             `json:"retrievalMetadata"`
	ConversationEmbedding pgvector.Vector    `json:"conversationEmbedding"`
	Similarity            float64            `json:"similarity"`
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]SearchMemoriesRow, error) {
	rows, err := q.db.Query(ctx, searchMemories,
		arg.Embedding,
		arg.UserID,
		arg.KgID,
		arg.SessionID,
		arg.ExcludePairIds,
		arg.MinSimilarity,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesRow
	for rows.Next() {
		var i SearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirestorePairID,
			&i.UserID,
			&i.KgID,
			&i.SessionID,
			&i.Title,
			&i.Description,
			&i.Prompt,
			&i.Response,
			&i.Input,
			&i.Output,
			&i.Source,
			&i.SourceContext,
			&i.Timestamp,
			&i.TimezoneOffset,
			&i.SeedMemories,
			&i.RetrievalMetadata,
			&i.ConversationEmbedding,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemoriesBySubject = `-- name: SearchMemoriesBySubject :many
SELECT mp.id, mp.firestore_pair_id, mp.user_id, mp.kg_id, mp.session_id, mp.title, mp.description,
    mp.prompt, mp.response, mp.input, mp.output, mp.source, mp.source_context, mp.timestamp,
    mp.timezone_offset, mp.seed_memories, mp.retrieval_metadata, mp.conversation_embedding,
    (1 - (mp.conversation_embedding <=> $1::vector))::float8 AS similarity
FROM memory_pairs mp
JOIN subject_memory_pair_links smpl ON smpl.pair_id = mp.id
WHERE smpl.subject_id = $2 AND mp.user_id = $3
  AND mp.conversation_embedding IS NOT NULL
  AND (1 - (mp.conversation_embedding <=> $1::vector)) >= $4::float8
ORDER BY mp.conversation_embedding <=> $1::vector, mp.timestamp DESC
LIMIT $5
`

type SearchMemoriesBySubjectParams struct {
	Embedding     pgvector.Vector `json:"embedding"`
	SubjectID     pgtype.UUID     `json:"subjectId"`
	UserID        string          `json:"userId"`
	MinSimilarity float64         `json:"minSimilarity"`
	LimitCount    int32           `json:"limitCount"`
}

type SearchMemoriesBySubjectRow struct {
	ID                    pgtype.UUID        `json:"id"`
	FirestorePairID       string             `json:"firestorePairId"`
	UserID                string             `json:"userId"`
	KgID                  string             `json:"kgId"`
	SessionID             pgtype.Text        `json:"sessionId"`
	Title                 pgtype.Text        `json:"title"`
	Description           pgtype.Text        `json:"description"`
	Prompt                pgtype.Text        `json:"prompt"`
	Response              pgtype.Text        `json:"response"`
	Input                 []byte             `json:"input"`
	Output                []byte             `json:"output"`
	Source                pgtype.Text        `json:"source"`
	SourceContext         pgtype.Text        `json:"sourceContext"`
	Timestamp             pgtype.Timestamptz `json:"timestamp"`
	TimezoneOffset        pgtype.Int4        `json:"timezoneOffset"`
	SeedMemories          []byte             `json:"seedMemories"`
	RetrievalMetadata     []byte             `json:"retrievalMetadata"`
	ConversationEmbedding pgvector.Vector    `json:"conversationEmbedding"`
	Similarity            float64            `json:"similarity"`
}

func (q *Queries) SearchMemoriesBySubject(ctx context.Context, arg SearchMemoriesBySubjectParams) ([]SearchMemoriesBySubjectRow, error) {
	rows, err := q.db.Query(ctx, searchMemoriesBySubject,
		arg.Embedding,
		arg.SubjectID,
		arg.UserID,
		arg.MinSimilarity,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMemoriesBySubjectRow
	for rows.Next() {
		var i SearchMemoriesBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.FirestorePairID,
			&i.UserID,
			&i.KgID,
			&i.SessionID,
			&i.Title,
			&i.Description,
			&i.Prompt,
			&i.Response,
			&i.Input,
			&i.Output,
			&i.Source,
			&i.SourceContext,
			&i.Timestamp,
			&i.TimezoneOffset,
			&i.SeedMemories,
			&i.RetrievalMetadata,
			&i.ConversationEmbedding,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubjects = `-- name: SearchSubjects :many
SELECT s.id, s.user_id, s.kg_id, s.subject_text, s.description_text, s.is_key_subject, s.embedding,
    (1 - (s.embedding <=> $1::vector))::float8 AS similarity,
    COUNT(smpl.pair_id)::bigint AS memory_count
FROM subjects s
LEFT JOIN subject_memory_pair_links smpl ON smpl.subject_id = s.id
WHERE s.user_id = $2 AND s.kg_id = $3
  AND s.embedding IS NOT NULL
  AND (1 - (s.embedding <=> $1::vector)) >= $4::float8
GROUP BY s.id
ORDER BY s.embedding <=> $1::vector, memory_count DESC, s.updated_at DESC
LIMIT $5
`

type SearchSubjectsParams struct {
	Embedding     pgvector.Vector `json:"embedding"`
	UserID        string          `json:"userId"`
	KgID          string          `json:"kgId"`
	MinSimilarity float64         `json:"minSimilarity"`
	LimitCount    int32           `json:"limitCount"`
}

type SearchSubjectsRow struct {
	ID              pgtype.UUID     `json:"id"`
	UserID          string          `json:"userId"`
	KgID            string          `json:"kgId"`
	SubjectText     string          `json:"subjectText"`
	DescriptionText pgtype.Text     `json:"descriptionText"`
	IsKeySubject    bool            `json:"isKeySubject"`
	Embedding       pgvector.Vector `json:"embedding"`
	Similarity      float64         `json:"similarity"`
	MemoryCount     int64           `json:"memoryCount"`
}

func (q *Queries) SearchSubjects(ctx context.Context, arg SearchSubjectsParams) ([]SearchSubjectsRow, error) {
	rows, err := q.db.Query(ctx, searchSubjects,
		arg.Embedding,
		arg.UserID,
		arg.KgID,
		arg.MinSimilarity,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSubjectsRow
	for rows.Next() {
		var i SearchSubjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KgID,
			&i.SubjectText,
			&i.DescriptionText,
			&i.IsKeySubject,
			&i.Embedding,
			&i.Similarity,
			&i.MemoryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubject = `-- name: UpsertSubject :one
INSERT INTO subjects (user_id, kg_id, subject_text, description_text, is_key_subject, embedding)
VALUES (
    $1, $2, $3,
    NULLIF($4, ''), $5, $6
)
ON CONFLICT (user_id, kg_id, subject_text) DO UPDATE SET
    description_text = COALESCE(EXCLUDED.description_text, subjects.description_text),
    is_key_subject = subjects.is_key_subject OR EXCLUDED.is_key_subject,
    embedding = COALESCE(EXCLUDED.embedding, subjects.embedding),
    updated_at = NOW()
RETURNING id, user_id, kg_id, subject_text, description_text, is_key_subject, embedding
`

type UpsertSubjectParams struct {
	UserID          string          `json:"userId"`
	KgID            string          `json:"kgId"`
	SubjectText     string          `json:"subjectText"`
	DescriptionText interface{}     `json:"descriptionText"`
	IsKeySubject    bool            `json:"isKeySubject"`
	Embedding       pgvector.Vector `json:"embedding"`
}

type UpsertSubjectRow struct {
	ID              pgtype.UUID     `json:"id"`
	UserID          string          `json:"userId"`
	KgID            string          `json:"kgId"`
	SubjectText     string          `json:"subjectText"`
	DescriptionText pgtype.Text     `json:"descriptionText"`
	IsKeySubject    bool            `json:"isKeySubject"`
	Embedding       pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (UpsertSubjectRow, error) {
	row := q.db.QueryRow(ctx, upsertSubject,
		arg.UserID,
		arg.KgID,
		arg.SubjectText,
		arg.DescriptionText,
		arg.IsKeySubject,
		arg.Embedding,
	)
	var i UpsertSubjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KgID,
		&i.SubjectText,
		&i.DescriptionText,
		&i.IsKeySubject,
		&i.Embedding,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO harness_users (uid) VALUES ($1)
ON CONFLICT (uid) DO NOTHING
`

func (q *Queries) UpsertUser(ctx context.Context, uid string) error {
	_, err := q.db.Exec(ctx, upsertUser, uid)
	return err
}
