// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type HarnessUser struct {
	ID        int64              `json:"id"`
	Uid       string             `json:"uid"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type MemoryPair struct {
	ID                    pgtype.UUID        `json:"id"`
	FirestorePairID       string             `json:"firestorePairId"`
	UserID                string             `json:"userId"`
	KgID                  string             `json:"kgId"`
	SessionID             pgtype.Text        `json:"sessionId"`
	Title                 pgtype.Text        `json:"title"`
	Description           pgtype.Text        `json:"description"`
	Prompt                pgtype.Text        `json:"prompt"`
	Response              pgtype.Text        `json:"response"`
	Input                 []byte             `json:"input"`
	Output                []byte             `json:"output"`
	Source                pgtype.Text        `json:"source"`
	SourceContext         pgtype.Text        `json:"sourceContext"`
	Timestamp             pgtype.Timestamptz `json:"timestamp"`
	TimezoneOffset        pgtype.Int4        `json:"timezoneOffset"`
	SeedMemories          []byte             `json:"seedMemories"`
	RetrievalMetadata     []byte             `json:"retrievalMetadata"`
	ConversationEmbedding pgvector.Vector    `json:"conversationEmbedding"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type RetrievalEvent struct {
	ID               int64              `json:"id"`
	UserID           string             `json:"userId"`
	KgID             string             `json:"kgId"`
	SessionID        string             `json:"sessionId"`
	RequestPath      string             `json:"requestPath"`
	Query            string             `json:"query"`
	QueryEmbedding   pgvector.Vector    `json:"queryEmbedding"`
	RetrievedPairIds []string           `json:"retrievedPairIds"`
	Weights          []byte             `json:"weights"`
	AuxFeatures      []byte             `json:"auxFeatures"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type Subject struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"userId"`
	KgID            string             `json:"kgId"`
	SubjectText     string             `json:"subjectText"`
	DescriptionText pgtype.Text        `json:"descriptionText"`
	IsKeySubject    bool               `json:"isKeySubject"`
	Embedding       pgvector.Vector    `json:"embedding"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type SubjectMemoryPairLink struct {
	SubjectID pgtype.UUID        `json:"subjectId"`
	PairID    pgtype.UUID        `json:"pairId"`
	UserID    string             `json:"userId"`
	KgID      string             `json:"kgId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}
